schema_version: 1

context:
  name: azure-mgmt-batchai
  version: 7.0.0b1

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/azure-mgmt-batchai-${{ version }}.zip
  sha256: 993eafbe359bab445642276e811db6f44f09795122a1b3c3dd703f9c333723a6

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - setuptools
    - python ${{ python_min }}.*
    - pip
  run:
    - python >=${{ python_min }}
    - azure-common >=1.1,<2.0
    - azure-mgmt-core >=1.2.0,<2.0
    - msrest >=0.6.21

tests:
  - python:
      imports:
        - azure.mgmt.batchai
        - azure.mgmt.batchai.aio
      pip_check: true
      python_version: ${{ python_min }}.*
about:
  summary: Microsoft Azure Batch AI Management Client Library for Python
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/Azure/azure-sdk-for-python

extra:
  recipe-maintainers:
    - janjagusch
